/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryDemoRouteImport } from './routes/try-demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WitnessIdRouteImport } from './routes/witness.$id'
import { Route as SettlementIdRouteImport } from './routes/settlement.$id'
import { Route as PactIdRouteImport } from './routes/pact.$id'

const TryDemoRoute = TryDemoRouteImport.update({
  id: '/try-demo',
  path: '/try-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WitnessIdRoute = WitnessIdRouteImport.update({
  id: '/witness/$id',
  path: '/witness/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementIdRoute = SettlementIdRouteImport.update({
  id: '/settlement/$id',
  path: '/settlement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PactIdRoute = PactIdRouteImport.update({
  id: '/pact/$id',
  path: '/pact/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/try-demo': typeof TryDemoRoute
  '/pact/$id': typeof PactIdRoute
  '/settlement/$id': typeof SettlementIdRoute
  '/witness/$id': typeof WitnessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/try-demo': typeof TryDemoRoute
  '/pact/$id': typeof PactIdRoute
  '/settlement/$id': typeof SettlementIdRoute
  '/witness/$id': typeof WitnessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/try-demo': typeof TryDemoRoute
  '/pact/$id': typeof PactIdRoute
  '/settlement/$id': typeof SettlementIdRoute
  '/witness/$id': typeof WitnessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/try-demo'
    | '/pact/$id'
    | '/settlement/$id'
    | '/witness/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/dashboard'
    | '/try-demo'
    | '/pact/$id'
    | '/settlement/$id'
    | '/witness/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/try-demo'
    | '/pact/$id'
    | '/settlement/$id'
    | '/witness/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  TryDemoRoute: typeof TryDemoRoute
  PactIdRoute: typeof PactIdRoute
  SettlementIdRoute: typeof SettlementIdRoute
  WitnessIdRoute: typeof WitnessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try-demo': {
      id: '/try-demo'
      path: '/try-demo'
      fullPath: '/try-demo'
      preLoaderRoute: typeof TryDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/witness/$id': {
      id: '/witness/$id'
      path: '/witness/$id'
      fullPath: '/witness/$id'
      preLoaderRoute: typeof WitnessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlement/$id': {
      id: '/settlement/$id'
      path: '/settlement/$id'
      fullPath: '/settlement/$id'
      preLoaderRoute: typeof SettlementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pact/$id': {
      id: '/pact/$id'
      path: '/pact/$id'
      fullPath: '/pact/$id'
      preLoaderRoute: typeof PactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  TryDemoRoute: TryDemoRoute,
  PactIdRoute: PactIdRoute,
  SettlementIdRoute: SettlementIdRoute,
  WitnessIdRoute: WitnessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
